install:
  - nginx
  - php-fpm
  - mariadb
  - redis
  
components:
  #--------------------------------#
  # Apache server                  #
  #---------+----------------------#
  # version | latest | default     #
  #---------+----------------------#
  apache:
    version: latest
  #--------------------------------#
  # Nginx                          #
  #---------+----------------------#
  # version | stable, mainline     #
  #---------+----------------------#
  nginx:
    version: stable
  #--------------------------------#
  # PHP-FPM                        #
  #---------+----------------------#
  # version | 7.2, 7.1, 7.0, 5.6   #
  # modules | see list             #
  #---------+----------------------#
  php-fpm:
    version: 7.2
    modules:
      - bcmath
      - bz2
      - cgi
      - cli
      - common
      - curl
      - dba
      - dev
      - enchant
      - gd
      - gmp
      - imap
      - interbase
      - intl
      - json
      - ldap
      - mbstring
      - mysql
      - odbc
      - opcache
      - pgsql
      - phpdbg
      - pspell
      - readline
      - recode
      - redis
      - snmp
      - soap
      - sqlite3
      - sybase
      - tidy
      - xml
      - xmlrpc
      - xsl
      - zip
  #--------------------------------#
  # Redis                          #
  #---------+----------------------#
  # version | latest | default     #
  #---------+----------------------#
  redis:
    version: latest
  #--------------------------------#
  # MariaDB                        #
  #-----------------+--------------#
  # version         | 10.2         #
  # password        | *            #
  # secure          | y, n         #
  # remote          | y, n         #
  # remote_user     | *            #
  # remote_password | *            #
  #-----------------+--------------#
  mariadb:
    version: 10.2
    password: 12345678
    secure: y
    remote: y
    remote_user: test_user
    remote_password: 12345678

